// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/watcher_service.proto

package watcher

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Food struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Food) Reset()         { *m = Food{} }
func (m *Food) String() string { return proto.CompactTextString(m) }
func (*Food) ProtoMessage()    {}
func (*Food) Descriptor() ([]byte, []int) {
	return fileDescriptor_60645ab0c4478b85, []int{0}
}

func (m *Food) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Food.Unmarshal(m, b)
}
func (m *Food) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Food.Marshal(b, m, deterministic)
}
func (m *Food) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Food.Merge(m, src)
}
func (m *Food) XXX_Size() int {
	return xxx_messageInfo_Food.Size(m)
}
func (m *Food) XXX_DiscardUnknown() {
	xxx_messageInfo_Food.DiscardUnknown(m)
}

var xxx_messageInfo_Food proto.InternalMessageInfo

func (m *Food) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FoodRequest struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodRequest) Reset()         { *m = FoodRequest{} }
func (m *FoodRequest) String() string { return proto.CompactTextString(m) }
func (*FoodRequest) ProtoMessage()    {}
func (*FoodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60645ab0c4478b85, []int{1}
}

func (m *FoodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodRequest.Unmarshal(m, b)
}
func (m *FoodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodRequest.Marshal(b, m, deterministic)
}
func (m *FoodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodRequest.Merge(m, src)
}
func (m *FoodRequest) XXX_Size() int {
	return xxx_messageInfo_FoodRequest.Size(m)
}
func (m *FoodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FoodRequest proto.InternalMessageInfo

func (m *FoodRequest) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type FoodResponse struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Delta                bool     `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Items                []*Food  `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodResponse) Reset()         { *m = FoodResponse{} }
func (m *FoodResponse) String() string { return proto.CompactTextString(m) }
func (*FoodResponse) ProtoMessage()    {}
func (*FoodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60645ab0c4478b85, []int{2}
}

func (m *FoodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodResponse.Unmarshal(m, b)
}
func (m *FoodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodResponse.Marshal(b, m, deterministic)
}
func (m *FoodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodResponse.Merge(m, src)
}
func (m *FoodResponse) XXX_Size() int {
	return xxx_messageInfo_FoodResponse.Size(m)
}
func (m *FoodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FoodResponse proto.InternalMessageInfo

func (m *FoodResponse) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *FoodResponse) GetDelta() bool {
	if m != nil {
		return m.Delta
	}
	return false
}

func (m *FoodResponse) GetItems() []*Food {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Food)(nil), "watcher.Food")
	proto.RegisterType((*FoodRequest)(nil), "watcher.FoodRequest")
	proto.RegisterType((*FoodResponse)(nil), "watcher.FoodResponse")
}

func init() { proto.RegisterFile("proto/watcher_service.proto", fileDescriptor_60645ab0c4478b85) }

var fileDescriptor_60645ab0c4478b85 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x3f, 0x4e, 0xc3, 0x30,
	0x14, 0xc6, 0xe5, 0xfe, 0xa1, 0xe4, 0x15, 0x2a, 0x64, 0xa5, 0x52, 0x94, 0x32, 0x44, 0x66, 0x20,
	0xea, 0x10, 0x43, 0xd9, 0x7a, 0x00, 0x26, 0xc4, 0x10, 0x06, 0xd8, 0x90, 0x49, 0x1f, 0xc5, 0x52,
	0x63, 0x07, 0xdb, 0x84, 0x9d, 0x2b, 0x70, 0x1b, 0xae, 0xc1, 0x15, 0x38, 0x08, 0x8a, 0x5d, 0x90,
	0x40, 0x62, 0x61, 0xf3, 0xfb, 0xde, 0xef, 0xfb, 0xfc, 0xd9, 0x30, 0x6b, 0x8c, 0x76, 0x9a, 0x3f,
	0x0b, 0x57, 0x3d, 0xa0, 0xb9, 0xb5, 0x68, 0x5a, 0x59, 0x61, 0xe1, 0x55, 0x3a, 0xda, 0xca, 0xe9,
	0xe1, 0x5a, 0xeb, 0xf5, 0x06, 0xb9, 0x68, 0x24, 0x17, 0x4a, 0x69, 0x27, 0x9c, 0xd4, 0xca, 0x06,
	0x8c, 0xa5, 0x30, 0x38, 0xd7, 0x7a, 0x45, 0x29, 0x0c, 0x94, 0xa8, 0x31, 0x21, 0x19, 0xc9, 0xa3,
	0xd2, 0x9f, 0xd9, 0x31, 0x8c, 0xbb, 0x5d, 0x89, 0x8f, 0x4f, 0x68, 0x1d, 0x4d, 0x60, 0xd4, 0xa2,
	0xb1, 0x52, 0x2b, 0x4f, 0x0d, 0xca, 0xaf, 0x91, 0x55, 0xb0, 0x17, 0x40, 0xdb, 0x68, 0x65, 0xf1,
	0x6f, 0x92, 0xc6, 0x30, 0x5c, 0xe1, 0xc6, 0x89, 0xa4, 0x97, 0x91, 0x7c, 0xb7, 0x0c, 0x03, 0x3d,
	0x82, 0xa1, 0x74, 0x58, 0xdb, 0xa4, 0x9f, 0xf5, 0xf3, 0xf1, 0x62, 0xbf, 0xd8, 0x76, 0x2f, 0x7c,
	0x6a, 0xd8, 0x2d, 0xde, 0x08, 0x4c, 0xae, 0x83, 0x7e, 0x15, 0x5e, 0x4a, 0x2f, 0x21, 0xba, 0x90,
	0xd6, 0x75, 0x94, 0xa5, 0xf1, 0x4f, 0x57, 0x28, 0x9d, 0x4e, 0x7f, 0xa9, 0xa1, 0x21, 0x8b, 0x5f,
	0xde, 0x3f, 0x5e, 0x7b, 0x13, 0x16, 0xf1, 0xf6, 0x94, 0xdf, 0x77, 0xfe, 0x25, 0x99, 0xd3, 0x1b,
	0x00, 0x7f, 0xc3, 0x3f, 0x02, 0x67, 0x3e, 0x70, 0xca, 0x0e, 0xbe, 0x03, 0xb9, 0x75, 0x06, 0x45,
	0xbd, 0x24, 0xf3, 0x13, 0x72, 0xb7, 0xe3, 0x7f, 0xfb, 0xec, 0x33, 0x00, 0x00, 0xff, 0xff, 0xf5,
	0xb3, 0x34, 0x40, 0xb3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WatcherServiceClient is the client API for WatcherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WatcherServiceClient interface {
	ListFoods(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*FoodResponse, error)
	WatchFoods(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (WatcherService_WatchFoodsClient, error)
}

type watcherServiceClient struct {
	cc *grpc.ClientConn
}

func NewWatcherServiceClient(cc *grpc.ClientConn) WatcherServiceClient {
	return &watcherServiceClient{cc}
}

func (c *watcherServiceClient) ListFoods(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*FoodResponse, error) {
	out := new(FoodResponse)
	err := c.cc.Invoke(ctx, "/watcher.WatcherService/ListFoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watcherServiceClient) WatchFoods(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (WatcherService_WatchFoodsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WatcherService_serviceDesc.Streams[0], "/watcher.WatcherService/WatchFoods", opts...)
	if err != nil {
		return nil, err
	}
	x := &watcherServiceWatchFoodsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WatcherService_WatchFoodsClient interface {
	Recv() (*FoodResponse, error)
	grpc.ClientStream
}

type watcherServiceWatchFoodsClient struct {
	grpc.ClientStream
}

func (x *watcherServiceWatchFoodsClient) Recv() (*FoodResponse, error) {
	m := new(FoodResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WatcherServiceServer is the server API for WatcherService service.
type WatcherServiceServer interface {
	ListFoods(context.Context, *FoodRequest) (*FoodResponse, error)
	WatchFoods(*FoodRequest, WatcherService_WatchFoodsServer) error
}

// UnimplementedWatcherServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWatcherServiceServer struct {
}

func (*UnimplementedWatcherServiceServer) ListFoods(ctx context.Context, req *FoodRequest) (*FoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFoods not implemented")
}
func (*UnimplementedWatcherServiceServer) WatchFoods(req *FoodRequest, srv WatcherService_WatchFoodsServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchFoods not implemented")
}

func RegisterWatcherServiceServer(s *grpc.Server, srv WatcherServiceServer) {
	s.RegisterService(&_WatcherService_serviceDesc, srv)
}

func _WatcherService_ListFoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatcherServiceServer).ListFoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watcher.WatcherService/ListFoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatcherServiceServer).ListFoods(ctx, req.(*FoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatcherService_WatchFoods_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FoodRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WatcherServiceServer).WatchFoods(m, &watcherServiceWatchFoodsServer{stream})
}

type WatcherService_WatchFoodsServer interface {
	Send(*FoodResponse) error
	grpc.ServerStream
}

type watcherServiceWatchFoodsServer struct {
	grpc.ServerStream
}

func (x *watcherServiceWatchFoodsServer) Send(m *FoodResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _WatcherService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "watcher.WatcherService",
	HandlerType: (*WatcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFoods",
			Handler:    _WatcherService_ListFoods_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchFoods",
			Handler:       _WatcherService_WatchFoods_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/watcher_service.proto",
}
